apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
        - name: mon-app
          image: bechir-lahouel/tpNote:latest
          ports:
            - containerPort: 3000

